Repository cdeler/woogle, pull requests merged in 2018-07, with the labels that each got.

#13 #1 Setup backend environments
  backend_application/.gitignore
  backend_application/Dockerfile
  backend_application/app/manage.py
  backend_application/app/woogle/__init__.py
  backend_application/app/woogle/settings.py
  backend_application/app/woogle/static/404.html
  backend_application/app/woogle/static/css/style.css
  backend_application/app/woogle/static/index.html
  backend_application/app/woogle/urls.py
  backend_application/app/woogle/views.py
  backend_application/app/woogle/wsgi.py
  backend_application/cmd.sh
  backend_application/config/nginx/nginx.conf
  backend_application/config/requirements.txt
  backend_application/docker-compose.dev.yml
  backend_application/docker-compose.env.yml
Labels: enhancement

#16 Dockerization
  dockerization/Dockerfile
  dockerization/app.py
  dockerization/docker-compose.yml
  dockerization/requirements.txt
Labels: enhancement

#19 Clear the repository
  log.txt
  wiki_indexer/Dockerfile
  wiki_indexer/app.py
  wiki_indexer/docker-compose.yml
  wiki_indexer/requirements.txt
Labels: invalid

#22 #10 Response processor implementation
  crawler/WikiPage.py
  crawler/WikiResponseProcessor.py
  crawler/WikiSpider.py
  crawler/requirements.txt
Labels: enhancement

#21 #15 script was updated
  dockerization/app.py
  dockerization/requirements.txt
Labels: enhancement

#20 #12 Connector between db and elastic has created
  wiki_indexer/app.ini
  wiki_indexer/app.py
  wiki_indexer/test_app.py
Labels: enhancement

#25 #24 Added arguments parser
  crawler/WikiResponseProcessor.py
  crawler/WikiSpider.py
Labels: enhancement

#26 #12 Second version of connector between db and elastic
  wiki_indexer/app.ini
  wiki_indexer/app.py
  wiki_indexer/connector.py
  wiki_indexer/requirements.txt
  wiki_indexer/test_app.py
Labels: duplicate

#40 #27 travis-ci added
  .travis.yml
  requirements.txt
Labels: enhancement

#36 #32 ListView for searching results
  backend_application/.gitignore
  backend_application/app/wikisearch/__init__.py
  backend_application/app/wikisearch/admin.py
  backend_application/app/wikisearch/apps.py
  backend_application/app/wikisearch/migrations/0001_initial.py
  backend_application/app/wikisearch/migrations/0002_article_page_rank.py
  backend_application/app/wikisearch/migrations/__init__.py
  backend_application/app/wikisearch/models.py
  backend_application/app/wikisearch/templates/404.html
  backend_application/app/wikisearch/templates/css/style.css
  backend_application/app/wikisearch/templates/index.html
  backend_application/app/wikisearch/tests.py
  backend_application/app/wikisearch/views.py
  backend_application/app/woogle/settings.py
  backend_application/app/woogle/urls.py
Labels: enhancement

#38 Database binding
  crawler/database_binding.py
  crawler/models.py
Labels: enhancement

#37 #30 DBWikiResponse
  backend_application/Dockerfile
  backend_application/app/woogle/settings.py
  backend_application/docker-compose.dev.yml
  backend_application/docker-compose.env.yml
  dockerization/Dockerfile
  dockerization/WikiResponseProcessor.py
  dockerization/app.py
  dockerization/requirements.txt
Labels: enhancement

#49 #33 Changed the format of the passed arguments in scrapy
  dockerization/app.py
Labels: bug

#51 #39 Extend functionality for django admin
  backend_application/app/wikisearch/admin.py
  backend_application/app/wikisearch/migrations/0003_auto_20180730_1249.py
  backend_application/app/wikisearch/migrations/0004_auto_20180730_2216.py
  backend_application/app/wikisearch/models.py
  backend_application/wait-postgres.sh
  wiki_indexer/app.ini
  wiki_indexer/app.py
  wiki_indexer/connector.py
  wiki_indexer/test_app.py
Labels: enhancement
